name: movie_analytics
version: "1.0.0"
config-version: 2

profile: movie_analytics

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  movie_analytics:
    +materialized: view
