movie_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER', 'itc6050') }}"
      password: "{{ env_var('DBT_PASSWORD', 'itc6050') }}"
      dbname: "{{ env_var('DBT_DBNAME', 'movies') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'analytics') }}"
      threads: 4
